# Generated by Django 4.0.5 on 2022-07-13 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FECODER_APP', '0003_usuario_clave_verificar_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categoria_post',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='FECODER_APP.categoria'),
        ),
    ]
