# Generated by Django 4.0.5 on 2022-07-13 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FECODER_APP', '0004_post_categoria_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categoria_post',
        ),
    ]
