# Generated by Django 4.0.5 on 2022-07-13 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FECODER_APP', '0005_remove_post_categoria_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
